--Deben haber 2 servidores conectados con sys y rol DBA sin 24

--SERVIDOR 1
show pdbs;

CREATE PLUGGABLE DATABASE WEB ADMIN USER uweb IDENTIFIED BY "lticPUCE24"
FILE_NAME_CONVERT = ('/u01/app/oracle/oradata/ORCL/pdbseed/', '/u01/app/oracle/oradata/ORCL/WEB/');

ALTER PLUGGABLE DATABASE WEB OPEN;

ALTER SESSION SET CONTAINER=WEB;

CREATE TABLESPACE DATOSEC
DATAFILE '/u01/app/oracle/oradata/ORCL/WEB/DATOSEC.dbf'
SIZE 1G AUTOEXTEND ON NEXT 500M;

CREATE TABLESPACE INDICESEC
DATAFILE '/u01/app/oracle/oradata/ORCL/WEB/INDICESEC.dbf'
SIZE 500M AUTOEXTEND ON NEXT 500M;

CREATE USER u_web IDENTIFIED BY lticPUCE24
DEFAULT TABLESPACE DATOSEC;

GRANT DBA, CONNECT, RESOURCE TO u_web WITH ADMIN OPTION;

CREATE DATABASE LINK link_admi
CONNECT TO u_admi IDENTIFIED BY lticPUCE24 USING 'admi';

CREATE TABLE CLIENTE (
 CLI_CEDULA VARCHAR2(13) PRIMARY KEY,
 EMP_CEDULA_RUC VARCHAR2(13),
 CLI_CORREO VARCHAR2(320),
 CLI_TELEFONO VARCHAR2(14)
) TABLESPACE DATOSEC;



--SERVIDOR 2
show pdbs;

CREATE PLUGGABLE DATABASE ADMI ADMIN USER uadmi IDENTIFIED BY "lticPUCE24"
FILE_NAME_CONVERT = ('/u01/app/oracle/oradata/ORCL/pdbseed/', '/u01/app/oracle/oradata/ORCL/ADMI/');

ALTER PLUGGABLE DATABASE ADMI OPEN;

ALTER SESSION SET CONTAINER = ADMI;

CREATE TABLESPACE DATOSAD
DATAFILE '/u01/app/oracle/oradata/ORCL/ADMI/DATOSAD.dbf'
SIZE 1G AUTOEXTEND ON NEXT 500M;

CREATE TABLESPACE INDICESAD
DATAFILE '/u01/app/oracle/oradata/ORCL/ADMI/INDICESAD.dbf'
SIZE 500M AUTOEXTEND ON NEXT 500M;

CREATE USER u_admi IDENTIFIED BY lticPUCE24
DEFAULT TABLESPACE DATOSAD;

GRANT DBA, CONNECT, RESOURCE TO u_admi WITH ADMIN OPTION;



--conectarse ocn los usuario creados:

--u_web:
CREATE DATABASE LINK link_admi
CONNECT TO u_admi IDENTIFIED BY lticPUCE24 USING 'admi';

CREATE TABLE CLIENTE (
 CLI_CEDULA VARCHAR2(13) PRIMARY KEY,
 EMP_CEDULA_RUC VARCHAR2(13),
 CLI_CORREO VARCHAR2(320),
 CLI_TELEFONO VARCHAR2(14)
) TABLESPACE DATOSEC;






--u_admi:
CREATE DATABASE LINK link_web
CONNECT TO u_web IDENTIFIED BY lticPUCE24 USING 'web';

CREATE TABLE EMPRESA (
 EMP_CEDULA_RUC VARCHAR2(13) PRIMARY KEY,
 EMP_NOMBRE VARCHAR2(120),
 EMP_DIRECCION VARCHAR2(200),
 EMP_TELEFONO VARCHAR2(14),
 EMP_CORREO VARCHAR2(300),
 EMP_REPRESENTANTE VARCHAR2(120),
 EMP_VALOR_IVA NUMBER(5,2),
 EMP_CODIGO_SRI VARCHAR2(13),
 EMP_PORCENTAJE_UTIL NUMBER(10,2)
) TABLESPACE DATOSAD;

CREATE TABLE CLIENTE (
 CLI_CEDULA VARCHAR2(13) PRIMARY KEY,
 EMP_CEDULA_RUC VARCHAR2(13),
 CLI_CORREO VARCHAR2(320),
 CLI_TELEFONO VARCHAR2(14)
) TABLESPACE DATOSAD;





--triggers:
CREATE OR REPLACE TRIGGER TRG_BD_EMPRESA
BEFORE DELETE ON EMPRESA
FOR EACH ROW
DECLARE
    v_dummy NUMBER;
BEGIN
    SELECT 1
    INTO v_dummy
    FROM CLIENTE
    WHERE EMP_CEDULA_RUC = :OLD.EMP_CEDULA_RUC
    AND ROWNUM = 1;

    RAISE_APPLICATION_ERROR(
        -20006,
        'No se puede eliminar la empresa: existen clientes asociados.'
    );
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        NULL;
END;
/

CREATE OR REPLACE TRIGGER TRG_BU_EMPRESA
BEFORE UPDATE OF EMP_CEDULA_RUC ON EMPRESA
FOR EACH ROW
DECLARE
    v_dummy NUMBER;
BEGIN
    IF :OLD.EMP_CEDULA_RUC <> :NEW.EMP_CEDULA_RUC THEN
        SELECT 1
        INTO v_dummy
        FROM CLIENTE
        WHERE EMP_CEDULA_RUC = :OLD.EMP_CEDULA_RUC
        AND ROWNUM = 1;

        RAISE_APPLICATION_ERROR(
            -20005,
            'No se puede modificar el RUC: existen clientes asociados.'
        );
    END IF;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        NULL;
END;
/


CREATE OR REPLACE TRIGGER TRG_BU_CLIENTE_EMPRESA
BEFORE UPDATE OF EMP_CEDULA_RUC ON CLIENTE
FOR EACH ROW
DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO v_count
    FROM EMPRESA
    WHERE EMP_CEDULA_RUC = :NEW.EMP_CEDULA_RUC;

    IF v_count = 0 THEN
        RAISE_APPLICATION_ERROR(
            -20001,
            'No existe la empresa ingresada.'
        );
    END IF;
END;
/

--trigger con replicación:
CREATE OR REPLACE TRIGGER TRG_CLIENTE_REPLICA
AFTER INSERT ON CLIENTE
FOR EACH ROW
BEGIN
 INSERT INTO CLIENTE@link_web
 VALUES (
  :NEW.CLI_CEDULA,
  :NEW.EMP_CEDULA_RUC,
  :NEW.CLI_CORREO,
  :NEW.CLI_TELEFONO
 );
END;
/


--en u_web:

CREATE OR REPLACE TRIGGER TRG_BU_CLIENTE_EMPRESA
BEFORE UPDATE OF EMP_CEDULA_RUC ON CLIENTE
FOR EACH ROW
DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO v_count
    FROM EMPRESA@link_admi
    WHERE EMP_CEDULA_RUC = :NEW.EMP_CEDULA_RUC;

    IF v_count = 0 THEN
        RAISE_APPLICATION_ERROR(
            -20001,
            'La empresa no existe en el servidor ADMIN.'
        );
    END IF;
END;
/




--en u_admi:
INSERT INTO EMPRESA (
    EMP_CEDULA_RUC,
    EMP_NOMBRE,
    EMP_DIRECCION,
    EMP_TELEFONO,
    EMP_CORREO,
    EMP_REPRESENTANTE,
    EMP_VALOR_IVA,
    EMP_CODIGO_SRI,
    EMP_PORCENTAJE_UTIL
) VALUES (
    '1790012345001',
    'PASTELERIA DULCE SABOR',
    'AV. AMAZONAS Y NACIONES UNIDAS',
    '0998765432',
    'CONTACTO@DULCESABOR.COM',
    'MARIA FERNANDA LOPEZ',
    15.00,
    'SRI-DS-001',
    20.50
);

INSERT INTO CLIENTE (
    CLI_CEDULA,
    EMP_CEDULA_RUC,
    CLI_CORREO,
    CLI_TELEFONO
) VALUES (
    '0912345678',
    '1790012345001',
    'CLIENTE.PRUEBA@MAIL.COM',
    '0981234567'
);

--debe fallar
UPDATE CLIENTE
SET EMP_CEDULA_RUC = '1790099999001'
WHERE CLI_CEDULA = '0912345678';

DELETE FROM EMPRESA
WHERE EMP_CEDULA_RUC = '1790012345001';

COMMIT; --activa la replicación




--en u_web:
SELECT * FROM CLIENTE;
--se podría ver la replicación





